name: Workflow for Building Packers and tests 
run-name:  NPM Test job and packer build 
env: 
  DB_USERNAME: ${{secrets.DB_USERNAME}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_HOST : ${{secrets.DB_HOST}}
  PORT: ${{secrets.NODE_PORT}} 
  NODE_PORT: ${{secrets.NODE_PORT}} # DECLARED FOR PACKER THE VARIABLE TO BE NODE_PORT to avoid confusion 
  # DB_NAME: ${{secrets.DB_NAME}}
  # GOOGLE_AUTH_SERVICE: ${{secrets.AUTH_CREDS}} # GOOGLE AUTH SERVICE credentials
  DB_DATABASE: ${{secrets.DB_DATABASE}}
  GOOGLE_PROJECT_ID: ${{secrets.GOOGLE_PROJECT_ID}}
  SOURCE_IMAGE_FAMILY: ${{secrets.SOURCE_IMAGE_FAMILY}}
  IMAGE_ZONE: ${{secrets.IMAGE_ZONE}}
  IMAGE_FAMILY: ${{secrets.IMAGE_FAMILY}}
  IMAGE_STORAGE_LOCATIONS: ${{secrets.IMAGE_STORAGE_LOCATIONS}}
  DISK_TYPE: ${{secrets.DISK_TYPE}}
  IMAGE_NAME: ${{secrets.IMAGE_NAME}}
on: 
  pull_request :
    types: 
      - closed
    branches: 
      - main
jobs:
  npm-test-and-packer-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Setup SQL 
        run:  |
          sudo service mysql start
          mysql -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB_DATABASE }};" -u${{ secrets.DB_USERNAME }} -p${{ secrets.DB_PASSWORD }}

      - uses: actions/checkout@v4
      - name: Installing NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 21.3.0
      - name: Installing Dependancies
        run: npm ci 
      - name : Run test
        run: npm test
      
      - name: Install Packer
        uses: hashicorp/setup-packer@main
        with:
          version: 1.10.1

      - name: Setting up zip for the packer 
        run: zip -r webapp-main.zip ./*

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.AUTH_CREDS }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      
      - name: packer downloading the binaries for the required provided 
        run:  packer init packer/templates/packer.pkr.hcl 

      - name: Status check to validate packer validate 
        run:  packer validate  packer/templates/packer.pkr.hcl

      - name: Build the packer image
        run: packer build packer/templates/packer.pkr.hcl
      
      - name: remove the zip file 
        run: rm -rf webapp-main.zip
